            - name: Setup MATLAB
  # You may pin to the exact commit or the version.
  # uses: matlab-actions/setup-matlab@b6c98f7926801316606ab9a0c4516b82e8271a2c
  uses: matlab-actions/setup-matlab@v2.6.1
  with:
    # MATLAB release to set up (R2021a or later)
    release: # optional, default is latest
    # Products to set up in addition to MATLAB, specified as a list of product names separated by spaces
    products: # optional, default is 
    # Option to enable caching with GitHub Actions, specified as false or true
    cache: # optional
          
